### ISSUE TITLE
Favicon doesn't work

### ISSUE THREAD

**Issue by thewindsofwinter** [afluffyfruit/catmath#1]
Hey, great site, just wanted to let you know that your favicon doesn't work because the path to the image isn't correct. Of course, it just means your image is so afraid of the OARSNESS of your site that it has decided to hide. Truly, fluff is all that is good ❤️ 

~~ffs lets hope my employer doesn't see this~~

**Comment by thewindsofwinter** [comment]
Probably can be fixed by removing the .. from the path tbh. Also: great site, I've starred the repo

**Comment by afluffyfruit** [comment]
Thanks ❤️ 

All the links should be fixed now, changed from relative paths to referencing the root directly :catlove:
